# Generated by Django 4.2.30 on 2026-06-05 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("waiting_on_customer", "Waiting on Customer"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("converted", "Converted to Work Order"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TicketReply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reply_type",
                    models.CharField(
                        choices=[
                            ("customer_visible", "Customer Visible"),
                            ("internal", "Internal Only"),
                        ],
                        db_index=True,
                        default="customer_visible",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_replies",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "reply_type"],
                        name="ticket_repl_ticket__93b01c_idx",
                    )
                ],
            },
        ),
    ]
