# Generated by Django 4.2.30 on 2026-06-07 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_default_checklists"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_locks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_locks",
            },
        ),
        migrations.CreateModel(
            name="TicketLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[("related", "Related"), ("duplicate", "Duplicate")],
                        default="related",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_as_a",
                        to="core.ticket",
                    ),
                ),
                (
                    "ticket_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_as_b",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_links",
                "unique_together": {("ticket_a", "ticket_b")},
            },
        ),
    ]
