# Generated by Django 4.2.30 on 2026-06-07 21:29

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_ticketlock_ticketlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_attachment_size_mb",
                    models.IntegerField(
                        default=25, help_text="Maximum file upload size in megabytes."
                    ),
                ),
                (
                    "blocked_extensions",
                    models.TextField(
                        default="exe,bat,sh,ps1,cmd,vbs,jar,msi,scr,pif",
                        help_text="Comma-separated list of blocked file extensions (without dots).",
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("local", "Local Filesystem"),
                            ("s3", "S3-Compatible (AWS, B2, MinIO, Wasabi)"),
                        ],
                        default="local",
                        help_text="Changing backends requires updating ATTACHMENT_STORAGE_BACKEND in .env and restarting.",
                        max_length=10,
                    ),
                ),
                (
                    "local_storage_path",
                    models.CharField(
                        blank=True,
                        help_text="Override for local storage path. Leave blank to use MEDIA_ROOT.",
                        max_length=500,
                    ),
                ),
                ("s3_bucket_name", models.CharField(blank=True, max_length=255)),
                ("s3_access_key", models.CharField(blank=True, max_length=255)),
                ("s3_secret_key", models.CharField(blank=True, max_length=255)),
                (
                    "s3_endpoint_url",
                    models.CharField(
                        blank=True,
                        help_text="For B2/MinIO/Wasabi. Leave blank for AWS S3.",
                        max_length=255,
                    ),
                ),
                ("s3_region", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "db_table": "site_settings",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(upload_to=core.models.attachment_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attachments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="attachments_content_7c0e26_idx",
                    )
                ],
            },
        ),
    ]
