# Generated by Django 4.2.30 on 2026-06-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_attachment_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("ticket_created", "Ticket Created (auto-responder)"),
                            ("reply_added", "Customer-Visible Reply Added"),
                            ("status_changed", "Status Changed"),
                            ("ticket_resolved", "Ticket Resolved"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Django template syntax. Variables: {{ ticket.ticket_number }}, {{ ticket.subject }}, {{ client.name }}, {{ status }}, {{ tech_name }}",
                        max_length=255,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Plain text body. Same template variables available."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email_templates",
                "ordering": ["trigger"],
            },
        ),
        migrations.CreateModel(
            name="SuppressedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why this address is suppressed.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Suppressed Addresses",
                "db_table": "suppressed_addresses",
                "ordering": ["email"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="suppress_emails",
            field=models.BooleanField(
                default=False,
                help_text="Suppress all automated outbound emails to this client.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Master switch — disabling this stops all automated outbound email.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_from",
            field=models.EmailField(
                blank=True,
                help_text="From address shown to clients. e.g. support@yourdomain.com",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_host",
            field=models.CharField(
                blank=True, help_text="e.g. mail.yourdomain.com", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_password",
            field=models.CharField(
                blank=True,
                help_text="Stored in plaintext — for internal use only.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_port",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_suppression_patterns",
            field=models.TextField(
                default="noreply@*\nno-reply@*\ndonotreply@*\nmailer-daemon@*\npostmaster@*\nbounce@*",
                help_text="One fnmatch pattern per line. Emails matching any pattern are suppressed.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="EmailSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(blank=True, max_length=254)),
                ("trigger", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("suppressed", "Suppressed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=50)),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_log",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "email_send_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
