# Generated by Django 4.2.30 on 2026-06-07 21:33

from django.db import migrations

TEMPLATES = [
    {
        'trigger': 'ticket_created',
        'subject_template': '[{{ ticket.ticket_number }}] We received your request — {{ ticket.subject }}',
        'body_template': (
            "Hi {{ client.name }},\n\n"
            "We've received your support request and assigned it ticket number {{ ticket.ticket_number }}.\n\n"
            "Subject: {{ ticket.subject }}\n\n"
            "We'll be in touch shortly. Please keep this ticket number handy for reference.\n\n"
            "Thanks,\n{{ site_name }}"
        ),
    },
    {
        'trigger': 'reply_added',
        'subject_template': '[{{ ticket.ticket_number }}] Update on your request',
        'body_template': (
            "Hi {{ client.name }},\n\n"
            "There's a new update on your support ticket {{ ticket.ticket_number }} — {{ ticket.subject }}.\n\n"
            "Please contact us to view the full message.\n\n"
            "Thanks,\n{{ site_name }}"
        ),
    },
    {
        'trigger': 'status_changed',
        'subject_template': '[{{ ticket.ticket_number }}] Status update: {{ status }}',
        'body_template': (
            "Hi {{ client.name }},\n\n"
            "The status of your support ticket {{ ticket.ticket_number }} has been updated to: {{ status }}\n\n"
            "Subject: {{ ticket.subject }}\n\n"
            "Thanks,\n{{ site_name }}"
        ),
    },
    {
        'trigger': 'ticket_resolved',
        'subject_template': '[{{ ticket.ticket_number }}] Your request has been resolved',
        'body_template': (
            "Hi {{ client.name }},\n\n"
            "Your support request {{ ticket.ticket_number }} — {{ ticket.subject }} — has been marked as resolved.\n\n"
            "If the issue recurs or you have further questions, please don't hesitate to reach out.\n\n"
            "Thanks,\n{{ site_name }}"
        ),
    },
]


def seed_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('core', 'EmailTemplate')
    for t in TEMPLATES:
        EmailTemplate.objects.get_or_create(trigger=t['trigger'], defaults={
            'subject_template': t['subject_template'],
            'body_template': t['body_template'],
            'is_active': True,
        })


def unseed_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('core', 'EmailTemplate')
    EmailTemplate.objects.filter(trigger__in=[t['trigger'] for t in TEMPLATES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_email_outbound_autoresponder'),
    ]

    operations = [
        migrations.RunPython(seed_templates, unseed_templates),
    ]
