# Generated by Django 4.2.30 on 2026-06-07 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_seed_email_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="KBCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "KB Category",
                "verbose_name_plural": "KB Categories",
                "db_table": "kb_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System roles cannot be deleted."
                    ),
                ),
                (
                    "can_manage_settings",
                    models.BooleanField(
                        default=False, help_text="Access admin panel and SiteSettings."
                    ),
                ),
                (
                    "can_view_all_tickets",
                    models.BooleanField(
                        default=False, help_text="View all tickets (vs. own only)."
                    ),
                ),
                (
                    "can_close_tickets",
                    models.BooleanField(
                        default=False, help_text="Resolve and close tickets."
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, help_text="Create and manage user accounts."
                    ),
                ),
                (
                    "can_view_reports",
                    models.BooleanField(
                        default=False, help_text="Access reporting section (Batch 6)."
                    ),
                ),
                (
                    "can_view_restricted_kb",
                    models.BooleanField(
                        default=False, help_text="View admin-only KB articles."
                    ),
                ),
                (
                    "can_manage_kb",
                    models.BooleanField(
                        default=False, help_text="Create and edit KB articles."
                    ),
                ),
                ("can_create_ticket", models.BooleanField(default=True)),
                ("can_edit_ticket", models.BooleanField(default=True)),
                ("can_delete_ticket", models.BooleanField(default=False)),
                ("can_assign_ticket", models.BooleanField(default=True)),
                ("can_reply_internal", models.BooleanField(default=True)),
                ("can_reply_customer", models.BooleanField(default=True)),
                ("can_create_workorder", models.BooleanField(default=True)),
                ("can_edit_workorder", models.BooleanField(default=True)),
                ("can_close_workorder", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SLAPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "grace_period_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Hours from ticket creation until overdue.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_transient",
                    models.BooleanField(
                        default=False,
                        help_text="Transient SLAs apply to short-lived tickets (e.g. same-day callbacks).",
                    ),
                ),
                (
                    "disable_overdue_alerts",
                    models.BooleanField(
                        default=False,
                        help_text="Suppress overdue badges for tickets on this plan.",
                    ),
                ),
            ],
            options={
                "db_table": "sla_plans",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TechSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "tech_skills",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="due_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Calculated from SLA grace period on assignment.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="overdue_acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="overdue_acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overdue_acknowledgments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="HelpTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "default_sla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_topics",
                        to="core.slaplan",
                    ),
                ),
            ],
            options={
                "db_table": "help_topics",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="help_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="core.helptopic",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="core.slaplan",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="Role-based permission set. Replaces the legacy role field.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="core.techskill"
            ),
        ),
        migrations.CreateModel(
            name="KBArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("troubleshooting", "Troubleshooting"),
                            ("how_to", "How-To"),
                            ("vendor", "Vendor Info"),
                            ("internal", "Internal Procedure"),
                        ],
                        db_index=True,
                        default="how_to",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="Restricted articles are visible only to users with can_view_restricted_kb.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="core.kbcategory",
                    ),
                ),
            ],
            options={
                "db_table": "kb_articles",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="kb_articles_categor_234499_idx",
                    ),
                    models.Index(
                        fields=["article_type", "is_active"],
                        name="kb_articles_article_40c66f_idx",
                    ),
                ],
            },
        ),
    ]
