# Generated by Django 4.2.30 on 2026-06-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_seed_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_default_client_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="When no client matches the sender email, new tickets are filed under a new client. Leave blank to auto-name from the sender email domain.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_delete_after_fetch",
            field=models.BooleanField(
                default=False,
                help_text="Delete messages after processing (IMAP). POP3 always deletes. Default: mark as read.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_email_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable polling the mailbox for incoming tickets and replies.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_folder",
            field=models.CharField(
                default="INBOX",
                help_text="IMAP folder to poll. Ignored for POP3.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_host",
            field=models.CharField(
                blank=True, help_text="e.g. mail.yourdomain.com", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_password",
            field=models.CharField(
                blank=True,
                help_text="Stored in plaintext — internal use only.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_port",
            field=models.IntegerField(
                default=993,
                help_text="993 for IMAP SSL, 995 for POP3 SSL, 143/110 without SSL.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_protocol",
            field=models.CharField(
                choices=[("imap", "IMAP"), ("pop3", "POP3")],
                default="imap",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_ssl",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inbound_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="strip_quoted_replies",
            field=models.BooleanField(
                default=True,
                help_text="Strip quoted reply text (> lines, On … wrote: blocks) from inbound replies.",
            ),
        ),
        migrations.CreateModel(
            name="InboundEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Email Message-ID header.",
                        max_length=500,
                    ),
                ),
                ("from_email", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new_ticket", "Created New Ticket"),
                            ("reply", "Added Reply to Ticket"),
                            ("duplicate", "Duplicate — Already Processed"),
                            ("error", "Processing Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_log",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "inbound_email_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
