# Generated by Django 4.2.30 on 2026-06-07 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_batch5_inbound_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row",
                    models.CharField(
                        choices=[("ticket", "Tickets"), ("workorder", "Work Orders")],
                        max_length=12,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "status_filter",
                    models.JSONField(
                        default=list,
                        help_text="List of status values to count. Empty = count all.",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="URL the tile links to. Use relative paths.",
                        max_length=200,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "visible_to",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("admin", "Admins Only"),
                            ("tech", "Techs Only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Optional emoji icon.", max_length=10
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_tiles",
                "ordering": ["row", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TicketQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "filter_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keys: status (list), assigned_to (int), help_topic (int), sla_plan (int), overdue (bool), client (int)",
                    ),
                ),
                ("sort_field", models.CharField(default="created_at", max_length=50)),
                (
                    "sort_direction",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="desc",
                        max_length=4,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a system queue visible to all users.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ticket_queues",
                "ordering": ["name"],
            },
        ),
    ]
