# Generated by Django 4.2.30 on 2026-06-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0013_add_ticket_assigned_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text (single line)"),
                            ("textarea", "Text Area (multi-line)"),
                            ("select", "Dropdown Select"),
                            ("checkbox", "Checkbox (yes/no)"),
                            ("date", "Date"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("ticket", "Tickets"),
                            ("workorder", "Work Orders"),
                            ("both", "Both"),
                        ],
                        default="ticket",
                        max_length=10,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "scoped_to_help_topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only show on tickets with this help topic. Leave blank for all tickets.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_fields",
                        to="core.helptopic",
                    ),
                ),
                (
                    "scoped_to_repair_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only show on work orders with this repair type. Leave blank for all work orders.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_fields",
                        to="core.repairtype",
                    ),
                ),
            ],
            options={
                "db_table": "custom_fields",
                "ordering": ["applies_to", "sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="core.customfield",
                    ),
                ),
            ],
            options={
                "db_table": "custom_field_choices",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("value", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="core.customfield",
                    ),
                ),
            ],
            options={
                "db_table": "custom_field_values",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="custom_fiel_content_c125ab_idx",
                    )
                ],
                "unique_together": {("content_type", "object_id", "field")},
            },
        ),
    ]
