# Generated by Django 4.2.30 on 2026-06-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_batch7_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="require_mfa",
            field=models.BooleanField(
                default=False,
                help_text="Force all users to enroll in TOTP two-factor authentication before accessing the app.",
            ),
        ),
    ]
