# Generated by Django 4.2.30 on 2026-06-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_batch8_mfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="mileage",
            name="trip_type",
            field=models.CharField(
                choices=[("one_way", "One-Way"), ("round_trip", "Round Trip")],
                default="round_trip",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_maps_api_key",
            field=models.CharField(
                blank=True,
                help_text="Google Maps API key with Distance Matrix API enabled. Restrict to Distance Matrix API in Google Cloud Console.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_address",
            field=models.CharField(
                blank=True,
                help_text="Shop address used as the origin for onsite mileage calculations (e.g. 235 Coolidge St. Silverton Oregon 97381).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("in_shop", "In-Shop"),
                    ("onsite", "Onsite"),
                    ("remote", "Remote"),
                ],
                default="in_shop",
                max_length=20,
            ),
        ),
    ]
