# Generated by Django 4.2.30 on 2026-06-08 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_batch9_mileage_maps"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickLaborItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Button label shown to techs, e.g. "Virus / Malware Removal"',
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text='Groups buttons by category, e.g. "Software"',
                        max_length=100,
                    ),
                ),
                (
                    "print_description",
                    models.TextField(
                        blank=True,
                        help_text="Client-facing description printed on the repair report. Leave blank to use the label.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "quick_labor_items",
                "ordering": ["category", "sort_order", "label"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full address, e.g. 235 Coolidge St., Silverton, OR 97381",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                help_text="PNG, JPG, or SVG. Displayed on repair reports and the nav bar.",
                null=True,
                upload_to="company/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your business name. Appears on repair reports and the nav bar.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.CreateModel(
            name="WorkPerformed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labor_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logged_entries",
                        to="core.quicklaboritem",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_performed_logged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_performed",
                        to="core.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "work_performed",
                "ordering": ["labor_item__category", "labor_item__label"],
            },
        ),
    ]
