# Generated by Django 4.2.30 on 2026-06-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_batch10_company_quicklabor"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("residential", "Residential"), ("business", "Business")],
                default="residential",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="receives_email",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to suppress automated emails to this contact.",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="device_password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="workorder",
            name="device_pin",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="workorder",
            name="device_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30)),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("cell", "Cell"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("other", "Other"),
                        ],
                        default="cell",
                        max_length=10,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="core.contact",
                    ),
                ),
            ],
            options={
                "db_table": "contact_phones",
                "ordering": ["phone_type", "number"],
            },
        ),
    ]
