# Generated by Django 4.2.30 on 2026-06-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_batch10_p2_contacts_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="assigned_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="core.contact",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="condition_at_intake",
            field=models.CharField(
                blank=True,
                choices=[("used", "Used"), ("new", "New"), ("damaged", "Damaged")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="os",
            field=models.CharField(
                blank=True,
                choices=[
                    ("windows", "Windows"),
                    ("macos", "macOS"),
                    ("linux", "Linux"),
                    ("ios", "iOS"),
                    ("android", "Android"),
                    ("chromeos", "ChromeOS"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="os_version",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
