# Generated by Django 4.2.30 on 2026-06-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_device_add_os_condition_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="core.contact",
            ),
        ),
    ]
