# Generated by Django 4.2.30 on 2026-06-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_workorder_add_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactphone",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Optional custom label, e.g. 'Mom's cell'",
                max_length=50,
            ),
        ),
    ]
