# Generated by Django 4.2.30 on 2026-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_contactphone_add_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="credential_notes",
            field=models.TextField(
                blank=True,
                help_text="Freeform credential notes, e.g. recovery email, security question answers",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="invoice_ninja_ref",
            field=models.CharField(
                blank=True,
                help_text="Invoice Ninja invoice reference number",
                max_length=100,
            ),
        ),
    ]
