# Generated by Django 4.2.30 on 2026-06-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_checklistitem_flat_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="color_accent",
            field=models.CharField(blank=True, default="#2563eb", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_primary",
            field=models.CharField(blank=True, default="#111827", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_status_assigned",
            field=models.CharField(blank=True, default="#ede9fe", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_status_cancelled",
            field=models.CharField(blank=True, default="#fee2e2", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_status_closed",
            field=models.CharField(blank=True, default="#f3f4f6", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_status_completed",
            field=models.CharField(blank=True, default="#dcfce7", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_status_in_progress",
            field=models.CharField(blank=True, default="#fef9c3", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_status_new",
            field=models.CharField(blank=True, default="#dbeafe", max_length=7),
        ),
        migrations.AlterField(
            model_name="cannedresponse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cannedresponsecategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
