# Generated by Django 4.2.30 on 2026-06-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_batch11_address_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="color_nav_text",
            field=models.CharField(blank=True, default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_sidebar_bg",
            field=models.CharField(blank=True, default="#1f2937", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_sidebar_text",
            field=models.CharField(blank=True, default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo shown in the nav bar. PNG or SVG recommended. Leave blank to show text.",
                null=True,
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_address_line1",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Street address, e.g. 235 Coolidge St.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_address_line2",
            field=models.CharField(
                blank=True,
                default="",
                help_text="City, State ZIP, e.g. Silverton, OR 97381",
                max_length=255,
            ),
        ),
    ]
