# Generated by Django 4.2.30 on 2026-06-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_batch12_branding_colors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workperformed",
            options={"ordering": ["logged_at"]},
        ),
        migrations.AddField(
            model_name="workperformed",
            name="custom_label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="workperformed",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="workperformed",
            name="labor_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logged_entries",
                to="core.quicklaboritem",
            ),
        ),
    ]
