# Generated by Django 4.2.30 on 2026-06-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_work_performed_customizable"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderitem",
            name="post_check",
            field=models.CharField(
                blank=True,
                choices=[("", "—"), ("pass", "Pass"), ("fail", "Fail"), ("na", "N/A")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="workorderitem",
            name="pre_check",
            field=models.CharField(
                blank=True,
                choices=[("", "—"), ("pass", "Pass"), ("fail", "Fail"), ("na", "N/A")],
                default="",
                max_length=10,
            ),
        ),
    ]
