# Generated by Django 4.2.30 on 2026-06-09 18:05

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_checklist_pre_post_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="email_password",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="inbound_password",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="credential_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                help_text="Freeform credential notes, e.g. recovery email, security question answers",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="device_password",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="device_pin",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="device_username",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
