# Generated by Django 4.2.30 on 2026-06-09 19:45

from django.db import migrations, models
import django.db.models.deletion


def backfill_invoices(apps, schema_editor):
    WorkOrder = apps.get_model('core', 'WorkOrder')
    Invoice = apps.get_model('core', 'Invoice')
    existing = set(Invoice.objects.values_list('work_order_id', flat=True))
    Invoice.objects.bulk_create([
        Invoice(work_order_id=wo_id)
        for wo_id in WorkOrder.objects.values_list('id', flat=True)
        if wo_id not in existing
    ])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_dashboard_tile_icon_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_status",
                    models.CharField(
                        choices=[
                            ("uninvoiced", "Uninvoiced"),
                            ("invoiced", "Invoiced"),
                            ("paid", "Paid"),
                            ("paid_direct", "Paid Direct"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="uninvoiced",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("invoiced_date", models.DateField(blank=True, null=True)),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("card", "Card"),
                            ("transfer", "Transfer"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="core.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
            },
        ),
        migrations.RunPython(backfill_invoices, migrations.RunPython.noop),
    ]
