# Generated by Django 4.2.30 on 2026-06-09 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_invoice_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "username",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("remote", "Remote Support"),
                            ("cloud", "Cloud"),
                            ("network", "Network"),
                            ("vendor", "Vendor"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                ("notes", encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                (
                    "admin_only",
                    models.BooleanField(
                        default=False, help_text="Restrict to administrators only"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_credentials_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CredentialAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("viewed", "Viewed"),
                            ("edited", "Edited"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="core.orgcredential",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
    ]
