# Generated by Django 4.2.30 on 2026-06-09 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_org_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="credential_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="device",
            name="device_password",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="device",
            name="device_username",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="role",
            name="can_view_device_credentials",
            field=models.BooleanField(
                default=False,
                help_text="Reveal encrypted device credentials (username/password).",
            ),
        ),
        migrations.CreateModel(
            name="DeviceCredentialAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("viewed", "Viewed"), ("edited", "Edited")],
                        max_length=20,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        help_text="Which field was revealed (username/password)",
                        max_length=50,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_logs",
                        to="core.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
    ]
