# Generated by Django 4.2.30 on 2026-06-09 21:54

from django.db import migrations, models


def seed_status_definitions(apps, schema_editor):
    StatusDefinition = apps.get_model('core', 'StatusDefinition')
    ticket_statuses = [
        ('new',                  'New',                      '#DBEAFE', 10),
        ('open',                 'Open',                     '#E0E7FF', 20),
        ('in_progress',          'In Progress',              '#FEF9C3', 30),
        ('waiting_on_customer',  'Waiting on Customer',      '#FED7AA', 40),
        ('resolved',             'Resolved',                 '#DCFCE7', 50),
        ('closed',               'Closed',                   '#F3F4F6', 60),
        ('converted',            'Converted to Work Order',  '#F3E8FF', 70),
    ]
    for slug, label, color, order in ticket_statuses:
        StatusDefinition.objects.get_or_create(
            entity_type='ticket', slug=slug,
            defaults=dict(label=label, color=color, is_system=True, sort_order=order),
        )
    wo_statuses = [
        ('new',         'New',         '#DBEAFE', 10),
        ('assigned',    'Assigned',    '#EDE9FE', 20),
        ('in_progress', 'In Progress', '#FEF9C3', 30),
        ('completed',   'Completed',   '#DCFCE7', 40),
        ('closed',      'Closed',      '#F3F4F6', 50),
        ('cancelled',   'Cancelled',   '#FEE2E2', 60),
    ]
    for slug, label, color, order in wo_statuses:
        StatusDefinition.objects.get_or_create(
            entity_type='workorder', slug=slug,
            defaults=dict(label=label, color=color, is_system=True, sort_order=order),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_device_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(db_index=True, default="open", max_length=50),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(db_index=True, default="new", max_length=50),
        ),
        migrations.CreateModel(
            name="StatusDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("ticket", "Ticket"), ("workorder", "Work Order")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("slug", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#E5E7EB",
                        help_text="Background color hex (e.g. #DBEAFE)",
                        max_length=7,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System statuses cannot be deleted."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["entity_type", "sort_order", "label"],
                "unique_together": {("entity_type", "slug")},
            },
        ),
        migrations.RunPython(seed_status_definitions, migrations.RunPython.noop),
    ]
