# Generated by Django 4.2.30 on 2026-06-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_status_definitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="core.contact",
            ),
        ),
    ]
