# Generated by Django 4.2.30 on 2026-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_ticket_wo_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="color_page_bg",
            field=models.CharField(blank=True, default="#f1f5f9", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_page_title",
            field=models.CharField(blank=True, default="#111827", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_section_header",
            field=models.CharField(blank=True, default="#f8fafc", max_length=7),
        ),
    ]
