# Generated by Django 4.2.30 on 2026-06-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_sitesettings_page_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="color_title_bar",
            field=models.CharField(blank=True, default="#ffffff", max_length=7),
        ),
    ]
