# Generated by Django 4.2.30 on 2026-06-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_sitesettings_title_bar_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Exact address or fnmatch pattern (e.g. spam@example.com or *@badomain.com).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "blocked_senders",
                "ordering": ["pattern"],
            },
        ),
    ]
