# Generated by Django 4.2.30 on 2026-06-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_blocked_senders"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="color_section_header_text",
            field=models.CharField(blank=True, default="#111827", max_length=7),
        ),
    ]
