# Generated by Django 4.2.30 on 2026-06-11 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_section_header_text_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. Use blank lines between paragraphs. Rendered with line breaks in HTML emails."
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used when a template has no signature assigned.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email_signatures",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="signature",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to use the default signature.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="core.emailsignature",
            ),
        ),
    ]
