# Generated by Django 4.2.30 on 2026-06-11 17:38

from django.db import migrations, models


def blank_serials_to_null(apps, schema_editor):
    """Convert existing empty-string serials to NULL so multiple serial-less
    devices can coexist (NULLs are distinct under the unique constraint)."""
    Device = apps.get_model('core', 'Device')
    Device.objects.filter(serial_number='').update(serial_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_email_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(blank_serials_to_null, migrations.RunPython.noop),
    ]
