# Generated by Django 4.2.30 on 2026-06-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_device_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_header_color',
            field=models.CharField(blank=True, default='', help_text='Header bar color for outgoing emails (e.g. #1f5f5b). Leave blank to use the app Title Bar color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_logo',
            field=models.ImageField(blank=True, help_text='Logo shown in outgoing emails. Leave blank to use the company logo.', null=True, upload_to='email/'),
        ),
    ]
