# Generated by Django 4.2.30 on 2026-06-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_sitesettings_email_header_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Level required to take this ticket. Raised by Escalate; the current owner keeps it until a higher-level tech claims it.'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1, help_text='Escalation level. Tickets escalate upward; higher levels can take over escalated tickets.'),
        ),
    ]
