# Generated by Django 4.2.30 on 2026-06-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_ticket_escalation_level_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignment_unseen',
            field=models.BooleanField(db_index=True, default=False, help_text='True when transferred/assigned to a user by someone else, until that user first opens the ticket. Drives the "new to you" indicator.'),
        ),
    ]
