# Generated by Django 4.2.30 on 2026-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_email_greeting_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="subject_template",
            field=models.CharField(
                help_text="Django template syntax. Variables: {{ ticket.ticket_number }}, {{ ticket.subject }}, {{ customer_name }}, {{ client.name }}, {{ contact.first_name }}, {{ status }}, {{ tech_name }}",
                max_length=255,
            ),
        ),
    ]
