# Generated by Django 4.2.30 on 2026-06-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="login_logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo shown on the login page. Leave blank to show text. Detailed logos work well here.",
                null=True,
                upload_to="login/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                help_text="PNG, JPG, or SVG. Displayed on repair reports.",
                null=True,
                upload_to="company/",
            ),
        ),
    ]
