# Generated by Django 4.2.30 on 2026-06-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_admin_reset_flag(apps, schema_editor):
    """Existing admins must keep the reset capability: turn the new flag on for
    any role that can already manage users or settings."""
    Role = apps.get_model("core", "Role")
    Role.objects.filter(
        models.Q(can_manage_users=True) | models.Q(can_manage_settings=True)
    ).update(can_reset_user_mfa=True)


def unseed_admin_reset_flag(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_sitesettings_login_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_reset_user_mfa",
            field=models.BooleanField(
                default=False,
                help_text="Reset (clear) another user's two-factor devices for lost-device recovery.",
            ),
        ),
        migrations.CreateModel(
            name="MFAResetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "Web (admin)"), ("cli", "CLI (break-glass)")],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the reset. Null = CLI break-glass.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mfa_resets_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_resets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(seed_admin_reset_flag, unseed_admin_reset_flag),
    ]
