# Generated by Django 4.2.30 on 2026-06-19 17:48

from django.db import migrations, models


def seed_unsorted_client(apps, schema_editor):
    """Create the single system 'Unsorted / Unverified' triage bucket."""
    Client = apps.get_model('core', 'Client')
    if not Client.objects.filter(is_unsorted=True).exists():
        Client.objects.get_or_create(
            name='Unsorted / Unverified',
            defaults={'is_unsorted': True, 'is_active': True},
        )
        # Ensure the flag is set even if a client with that name already existed.
        Client.objects.filter(name='Unsorted / Unverified').update(is_unsorted=True)


def unseed_unsorted_client(apps, schema_editor):
    Client = apps.get_model('core', 'Client')
    Client.objects.filter(is_unsorted=True, name='Unsorted / Unverified').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_role_can_reset_user_mfa_mfaresetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_unsorted',
            field=models.BooleanField(default=False, help_text='System "Unsorted / Unverified" bucket: holds inbound tickets from senders not yet matched to a real client, pending triage. There should only ever be one.'),
        ),
        migrations.RunPython(seed_unsorted_client, unseed_unsorted_client),
    ]
