# Generated by Django 4.2.30 on 2026-06-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_client_is_unsorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cpu',
            field=models.CharField(blank=True, help_text="Processor, e.g. 'Intel Core i7-1185G7' or 'Apple M2'", max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='ram',
            field=models.CharField(blank=True, help_text="Physical memory, e.g. '16 GB'", max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='storage',
            field=models.CharField(blank=True, help_text="Disk, e.g. '512 GB SSD' or '1 TB NVMe + 2 TB HDD'", max_length=150),
        ),
    ]
