# Generated by Django 4.2.30 on 2026-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_device_cpu_device_ram_device_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='cpu',
            field=models.CharField(blank=True, help_text='Processor as serviced', max_length=150),
        ),
        migrations.AddField(
            model_name='workorder',
            name='ram',
            field=models.CharField(blank=True, help_text='Physical memory as serviced', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='storage',
            field=models.CharField(blank=True, help_text='Disk as serviced', max_length=150),
        ),
    ]
