# Generated by Django 4.2.30 on 2026-06-20 17:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_workorder_cpu_workorder_ram_workorder_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=core.models.private_attachment_storage, upload_to=core.models.attachment_upload_path),
        ),
    ]
