# Generated by Django 4.2.30 on 2026-06-20 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0057_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklaboritem',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Prefills the price when this button logs a line item. Leave blank for no price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('labor', 'Labor'), ('part', 'Part / Material')], db_index=True, default='labor', max_length=10)),
                ('description', models.CharField(help_text='Line label, e.g. "Virus removal" or "1TB SSD".', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Per-unit price. Blank = unpriced (not counted in the total).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items_logged', to=settings.AUTH_USER_MODEL)),
                ('source_labor_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='core.quicklaboritem')),
            ],
            options={
                'db_table': 'line_items',
                'ordering': ['logged_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='line_items_content_dee90f_idx'), models.Index(fields=['kind'], name='line_items_kind_ed48dd_idx')],
            },
        ),
    ]
