# Generated by Django 4.2.30 on 2026-06-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_migrate_workperformed_to_lineitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkPerformed',
        ),
    ]
