# Generated by Django 4.2.30 on 2026-06-20 22:19

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_delete_workperformed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_ninja_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_ninja_enabled',
            field=models.BooleanField(default=False, help_text='Enable the "Send to Invoice Ninja" action on work orders.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_ninja_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='IN API token (Settings → Account Management → Integrations → API Tokens). Stored encrypted.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_ninja_url',
            field=models.CharField(blank=True, help_text='Invoice Ninja API base URL. Cloud: https://invoicing.co — self-hosted: your server URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='invoice_ninja_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='invoice_ninja_ref',
            field=models.CharField(blank=True, help_text='Invoice Ninja invoice number (editable — record where the work actually landed if a draft was merged in IN)', max_length=100),
        ),
    ]
