# Generated by Django 4.2.30 on 2026-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_system_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="reported_problem",
            field=models.TextField(
                blank=True,
                help_text="Client's reported issue and any work requested; shown on the repair report",
            ),
        ),
    ]
