# Generated by Django 4.2.30 on 2026-06-24 16:23

from django.db import migrations, models


def backfill_first_responded(apps, schema_editor):
    """Stamp first_responded_at on tickets that already have a staff
    customer-visible reply, so the new 'first response meets SLA' rule applies
    retroactively and existing replied-to tickets stop showing overdue."""
    Ticket = apps.get_model('core', 'Ticket')
    TicketReply = apps.get_model('core', 'TicketReply')
    for ticket in Ticket.objects.all().iterator():
        first = (
            TicketReply.objects
            .filter(ticket=ticket, reply_type='customer_visible',
                    created_by__isnull=False)
            .order_by('created_at')
            .first()
        )
        if first:
            Ticket.objects.filter(pk=ticket.pk).update(
                first_responded_at=first.created_at
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_workorder_reported_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set on the first staff customer-visible reply. Once set, the response SLA is met and the ticket can no longer go overdue.', null=True),
        ),
        migrations.RunPython(backfill_first_responded, migrations.RunPython.noop),
    ]
