# Generated by Django 5.2.15 on 2026-06-29 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_ticket_first_responded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_view_prospects",
            field=models.BooleanField(
                default=True, help_text="View and manage sales prospects (leads)."
            ),
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_first_name", models.CharField(max_length=100)),
                ("contact_last_name", models.CharField(blank=True, max_length=100)),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="The company this contact belongs to, if any (required for business).",
                        max_length=255,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("business", "Business"),
                        ],
                        default="residential",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promoted_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_from_prospects",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "db_table": "prospects",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="prospects_status_a22ccb_idx"),
                    models.Index(fields=["email"], name="prospects_email_f91804_idx"),
                ],
            },
        ),
    ]
