# Generated by Django 5.2.15 on 2026-06-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_role_can_view_prospects_prospect"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="in_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="in_status_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_ninja_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
