# Generated by Django 5.2.15 on 2026-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_estimate_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email_sales_from",
            field=models.EmailField(
                blank=True,
                help_text="From address for quotes/estimates. Blank = use the support From address above.",
                max_length=254,
            ),
        ),
    ]
