# Generated by Django 5.2.15 on 2026-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_sale_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_ninja_ref',
            field=models.CharField(blank=True, help_text='Invoice Ninja invoice number (for display).', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_ninja_walkin_client_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
