# Generated by Django 5.2.15 on 2026-07-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_sale_checkout_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='contact',
        ),
    ]
