# Generated by Django 5.2.15 on 2026-07-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_remove_sale_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimateOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='e.g. "Budget", "Standard", "Premium".',
                        max_length=120,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.estimate",
                    ),
                ),
            ],
            options={
                "db_table": "estimate_options",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
