# Generated by Django 5.2.15 on 2026-07-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_estimateoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="general_label",
            field=models.CharField(default="General", max_length=120),
        ),
    ]
