# Generated by Django 5.2.15 on 2026-07-03 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_estimate_general_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="core.client",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="core.client",
            ),
        ),
    ]
