# Generated by Django 5.2.15 on 2026-07-04 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_alter_device_client_alter_workorder_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_managed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="In the recurring monthly billing group — appears on the Monthly Clients list.",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="monthly_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional. Pre-fills the monthly charge amount. Leave blank to enter it each month.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="is_recurring",
            field=models.BooleanField(
                default=False,
                help_text="This sale is a recurring monthly charge (Lane C), not a counter/walk-in sale.",
            ),
        ),
    ]
