# Generated by Django 5.2.15 on 2026-07-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_quicklaboritem_to_catalogitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_business_sla",
            field=models.ForeignKey(
                blank=True,
                help_text="Default SLA plan for business clients. New tickets inherit this unless one is picked manually.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.slaplan",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_residential_sla",
            field=models.ForeignKey(
                blank=True,
                help_text="Default SLA plan for residential clients (also covers the Unsorted bucket until triaged).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.slaplan",
            ),
        ),
    ]
