# Generated by Django 5.2.15 on 2026-07-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_sla_client_type_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ticket_reopen_window_days",
            field=models.PositiveIntegerField(
                default=14,
                help_text="A client reply to a closed/resolved ticket within this many days threads in and flags it for review, but leaves it closed — a tech reopens or dismisses it explicitly. Past the window, the reply starts a new ticket linked to the old one for context instead.",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text='Stamped when the ticket enters resolved/closed; cleared when it leaves those statuses. Gates the reply reopen window (Slice 4) — deliberately NOT stamped for "converted" (the work order is the active record there, not the ticket).',
                null=True,
            ),
        ),
    ]
