# Generated by Django 5.2.15 on 2026-07-08 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_ticket_reopen_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="billing_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Day of the month this managed client is billed (1–31). Nothing is hard-coded to the 1st — set each client to their own day. A day past the month end bills on the last day (e.g. 31 → Feb 28/29).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
