# Generated by Django 5.2.15 on 2026-07-09 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_client_billing_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_process_payments',
            field=models.BooleanField(default=False, help_text="Trigger a charge against a client's card on file in Invoice Ninja. Off by default — opt-in only."),
        ),
        migrations.CreateModel(
            name='PaymentChargeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ninja_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Server-computed amount at the moment of the attempt.', max_digits=10)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('success', 'Trigger Succeeded'), ('failed', 'Trigger Failed')], max_length=10)),
                ('in_status_after', models.CharField(blank=True, help_text='IN status read back immediately after the trigger (often still Draft/Sent — the charge is async).', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_charge_attempts', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_attempts', to='core.sale')),
            ],
            options={
                'db_table': 'payment_charge_attempts',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
