# Generated by Django 5.2.15 on 2026-07-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_role_can_process_payments_paymentchargeattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, help_text='Check number, Square confirmation, or other transaction reference — printed on the receipt.', max_length=100),
        ),
    ]
