# Generated by Django 5.2.15 on 2026-07-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_invoice_paid_at_invoice_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_view_org_credentials',
            field=models.BooleanField(default=False, help_text='Reveal the shared organization credential vault (Wi-Fi, portal logins, vendor accounts).'),
        ),
    ]
