# Generated by Django 5.2.16 on 2026-07-11 17:39

import encrypted_model_fields.fields
from django.db import migrations


def reencrypt_existing_values(apps, schema_editor):
    """The AlterFields above only change the Python field class — the
    underlying column was already a plain text column, so any existing
    plaintext value survives untouched on disk. EncryptedMixin.to_python()
    gracefully falls through to the raw value on InvalidToken, so reading a
    still-plaintext row through the (now-encrypted) field returns the
    plaintext unchanged; saving it back then encrypts it via
    get_db_prep_save. Safe to run on an empty value (blank stays blank) and
    idempotent (re-running on an already-encrypted value round-trips fine).
    """
    SiteSettings = apps.get_model("core", "SiteSettings")
    for settings in SiteSettings.objects.all():
        settings.save(update_fields=["google_maps_api_key", "s3_secret_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_role_can_view_org_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="google_maps_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Google Maps API key with Distance Matrix API enabled. Restrict to Distance Matrix API in Google Cloud Console.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="s3_secret_key",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.RunPython(reencrypt_existing_values, migrations.RunPython.noop),
    ]
