# Generated by Django 5.2.16 on 2026-07-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_encrypt_s3_secret_and_maps_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentchargeattempt",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge_attempts",
                to="core.workorder",
            ),
        ),
        migrations.AlterField(
            model_name="paymentchargeattempt",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge_attempts",
                to="core.sale",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentchargeattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sale__isnull", False), ("work_order__isnull", True)),
                    models.Q(("sale__isnull", True), ("work_order__isnull", False)),
                    _connector="OR",
                ),
                name="payment_charge_attempt_exactly_one_host",
            ),
        ),
    ]
