# Generated by Django 5.2.16 on 2026-07-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_payment_charge_attempt_work_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_backlog1_bg",
            field=models.CharField(blank=True, default="#eaf3de", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_backlog1_text",
            field=models.CharField(blank=True, default="#3b6d11", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_backlog2_bg",
            field=models.CharField(blank=True, default="#faeeda", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_backlog2_text",
            field=models.CharField(blank=True, default="#854f0b", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_backlog3_bg",
            field=models.CharField(blank=True, default="#faece7", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_backlog3_text",
            field=models.CharField(blank=True, default="#993c1d", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_backlog4_bg",
            field=models.CharField(blank=True, default="#fcebeb", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_backlog4_text",
            field=models.CharField(blank=True, default="#a32d2d", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_outstanding_bg",
            field=models.CharField(blank=True, default="#faeeda", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_outstanding_text",
            field=models.CharField(blank=True, default="#633806", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_ready_bg",
            field=models.CharField(blank=True, default="#eaf3de", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_ready_text",
            field=models.CharField(blank=True, default="#27500a", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_tickets_bg",
            field=models.CharField(blank=True, default="#e6f1fb", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_tickets_text",
            field=models.CharField(blank=True, default="#0c447c", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_workorders_bg",
            field=models.CharField(blank=True, default="#e1f5ee", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_dash_workorders_text",
            field=models.CharField(blank=True, default="#0f6e56", max_length=7),
        ),
    ]
