# Generated by Django 5.2.16 on 2026-07-13 20:10

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_sitesettings_color_dash_backlog1_bg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="backup_local_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text='For "Local / mounted drive": destination path on the server (e.g. /mnt/nas/mb-backups).',
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_offsite_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Disabled (local retention only)"),
                    ("local", "Local / mounted drive"),
                    ("s3", "S3-compatible (Backblaze B2, AWS S3, Wasabi, MinIO)"),
                ],
                default="",
                help_text="Where to send a second, off-box copy of each backup. Blank = keep local copies only.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_retention_local",
            field=models.PositiveIntegerField(
                default=14,
                help_text="How many recent backup archives to keep on the server.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_access_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="S3 access key ID. Stored encrypted."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_bucket",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 bucket name for backups.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_endpoint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 endpoint host (e.g. s3.us-west-002.backblazeb2.com).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional folder/prefix inside the bucket (e.g. murphys-bench).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_region",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 region (optional; some providers require it, e.g. us-west-002).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_secret_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="S3 secret access key. Stored encrypted."
            ),
        ),
    ]
