# Generated by Django 5.2.16 on 2026-07-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_sitesettings_backup_local_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="backup_local_path",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="backup_offsite_type",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="backup_retention_local",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_offsite_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Ship each backup offsite to an S3-compatible bucket.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_offsite_retention_mode",
            field=models.CharField(
                choices=[("count", "Keep N most recent"), ("age", "Keep N days")],
                default="age",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_offsite_retention_value",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Offsite retention: number of copies (count) or days (age).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Ship each backup to an onsite path (off-box: NAS/USB/other host).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Onsite destination path mounted on the server (e.g. /mnt/nas/mb-backups).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_retention_mode",
            field=models.CharField(
                choices=[("count", "Keep N most recent"), ("age", "Keep N days")],
                default="count",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_retention_value",
            field=models.PositiveIntegerField(
                default=14,
                help_text="Onsite retention: number of copies (count) or days (age).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_schedule_days",
            field=models.CharField(
                default="daily",
                help_text="'daily' or a CSV of weekday tokens (mon,tue,wed,thu,fri,sat,sun).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_schedule_times",
            field=models.CharField(
                default="02:00",
                help_text="CSV of HH:MM run times per day (e.g. 02:00,14:00).",
                max_length=255,
            ),
        ),
    ]
