# Generated by Django 5.2.16 on 2026-07-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_remove_sitesettings_backup_local_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="backup_schedule_days",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="backup_schedule_times",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_offsite_schedule_days",
            field=models.CharField(
                default="daily",
                help_text="Offsite schedule: 'daily' or CSV of weekday tokens (mon,tue,...).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_offsite_schedule_times",
            field=models.CharField(
                default="02:00",
                help_text="Offsite run times: CSV of HH:MM (e.g. 02:00).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_schedule_days",
            field=models.CharField(
                default="daily",
                help_text="Onsite schedule: 'daily' or CSV of weekday tokens (mon,tue,...).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_schedule_times",
            field=models.CharField(
                default="02:00",
                help_text="Onsite run times: CSV of HH:MM (e.g. 06:00,18:00).",
                max_length=255,
            ),
        ),
    ]
