# Generated by Django 5.2.16 on 2026-07-14 21:27

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_remove_sitesettings_backup_schedule_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="backup_onsite_path",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_folder",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional subfolder within the share (e.g. mb-backups).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_host",
            field=models.CharField(
                blank=True,
                default="",
                help_text="NAS IP address or hostname (e.g. 10.58.58.58).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_password",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Stored encrypted."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_share",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Share name on the NAS (e.g. VM).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_onsite_username",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="backup_onsite_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Ship each backup to an onsite NAS/network share (SMB).",
            ),
        ),
    ]
