# Generated by Django 5.2.16 on 2026-07-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_remove_sitesettings_backup_onsite_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Reception PC' or 'DC01'", max_length=255)),
                ('asset_type', models.CharField(choices=[('workstation', 'Workstation'), ('server', 'Server'), ('network', 'Network Device'), ('mobile', 'Mobile Device'), ('printer', 'Printer'), ('other', 'Other')], default='workstation', max_length=50)),
                ('identifier', models.CharField(blank=True, help_text='Asset tag, hostname, or serial number.', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.client')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['client', 'name'],
                'indexes': [models.Index(fields=['client', 'is_active'], name='assets_client__c55dfe_idx'), models.Index(fields=['asset_type'], name='assets_asset_t_fc4c39_idx')],
            },
        ),
    ]
