# Generated by Django 5.2.16 on 2026-07-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_contract_asset_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='billing_period',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_sales', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='This sale is a recurring charge (Lane C or a Contract), not a counter/walk-in sale.'),
        ),
    ]
