# Generated by Django 5.2.16 on 2026-07-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_sale_billing_period_sale_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='promoted_to_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.asset'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.asset'),
        ),
    ]
