# Generated by Django 5.2.16 on 2026-07-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_device_promoted_to_asset_workorder_asset'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False)), fields=('contract', 'billing_period'), name='uniq_contract_billing_period'),
        ),
    ]
