# Generated by Django 5.2.16 on 2026-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_sale_uniq_contract_billing_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('card', 'Card'), ('transfer', 'Transfer'), ('other', 'Other'), ('no_charge', 'No charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('card', 'Card'), ('other', 'Other'), ('no_charge', 'No charge')], max_length=20),
        ),
    ]
