# Generated by Django 5.2.16 on 2026-07-20 13:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_alter_invoice_payment_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketWorkLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("logged_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_work_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_work_logs",
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "logged_at"],
                        name="ticket_work_ticket__4e3d9f_idx",
                    )
                ],
            },
        ),
    ]
