# Generated by Django 5.2.16 on 2026-07-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_retire_workorder_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
