# Generated by Django 5.2.16 on 2026-07-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_notification_dismissed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='install_initialized_at',
            field=models.DateTimeField(blank=True, help_text='Set once when the install is first completed. Blocks demo-data seeding.', null=True),
        ),
    ]
