# Generated by Django 5.2.16 on 2026-08-15 05:10

from django.db import migrations, models


def hide_converted_from_the_dropdown(apps, schema_editor):
    """'Converted to Work Order' names an action it cannot perform.

    Choosing it in the ticket status dropdown renamed the ticket and created no
    work order, and drove the ticket into a state that hid the button that does
    the real conversion. Mike's call, Aug 14: remove it from the dropdown.

    The status itself is untouched. TicketConvertView still sets it, existing
    converted tickets keep it, it still displays, and it is still filterable in
    the ticket list and editable in Settings. It just cannot be set by hand.
    """
    StatusDefinition = apps.get_model('core', 'StatusDefinition')
    StatusDefinition.objects.filter(
        entity_type='ticket', slug='converted',
    ).update(operator_selectable=False)


def restore_converted_to_the_dropdown(apps, schema_editor):
    StatusDefinition = apps.get_model('core', 'StatusDefinition')
    StatusDefinition.objects.filter(
        entity_type='ticket', slug='converted',
    ).update(operator_selectable=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_remove_closed_work_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdefinition',
            name='operator_selectable',
            field=models.BooleanField(default=True, help_text='Uncheck for statuses only an action may set (e.g. Converted to Work Order). Hidden from the status dropdowns; still displayed and still filterable.'),
        ),
        migrations.RunPython(
            hide_converted_from_the_dropdown,
            restore_converted_to_the_dropdown,
        ),
    ]
