# Generated by Django 5.2.16 on 2026-08-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='ticket_reopen_window_days',
            field=models.PositiveIntegerField(default=14, help_text='A client reply to a resolved ticket within this many days threads in and flags it for review, but leaves it resolved; a tech reopens or dismisses it explicitly. When the window runs out the ticket is marked Closed automatically (no email to the client), and a later reply starts a new ticket linked to the old one.'),
        ),
    ]
