# Generated by Django 5.2.17 on 2026-08-21 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_reopen_window_help_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"ordering": ["trigger", "name"]},
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Custom templates only; event templates are named by their event.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="trigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ticket_created", "Ticket Created (auto-responder)"),
                    ("reply_added", "Customer-Visible Reply Added"),
                    ("status_changed", "Status Changed"),
                    ("ticket_resolved", "Ticket Resolved"),
                ],
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("thank_you", "Thank-you"),
                            ("satisfaction", "Satisfaction check"),
                            ("planned", "Planned touch"),
                            ("other", "Other"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("due_on", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="core.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="core.prospect",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Email to send when this follow-up is carried out.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="core.emailtemplate",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="core.ticket",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="core.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "follow_ups",
                "ordering": ["due_on", "created_at"],
            },
        ),
    ]
