# Generated by Django 5.2.17 on 2026-08-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_follow_ups_and_custom_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="color_room_desk",
            field=models.CharField(blank=True, default="#ae3ec9", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_room_office",
            field=models.CharField(blank=True, default="#6c7a91", max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="color_room_register",
            field=models.CharField(blank=True, default="#2fb344", max_length=7),
        ),
    ]
