# Generated by Django 5.2.17 on 2026-08-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_retire_old_frame_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="followup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("client__isnull", False), ("prospect__isnull", True)),
                    models.Q(("client__isnull", True), ("prospect__isnull", False)),
                    _connector="OR",
                ),
                name="follow_up_exactly_one_of_client_or_prospect",
            ),
        ),
    ]
