# Generated by Django 5.2.17 on 2026-08-26 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_follow_up_exactly_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='quick_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_new_ticket',
            field=models.BooleanField(default=True, help_text='Email the recipients below when a new ticket arrives.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_new_ticket_users',
            field=models.ManyToManyField(blank=True, help_text='Who is emailed about new tickets (and replies on unassigned tickets). Blank = every admin.', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
