# Generated by Django 5.2.17 on 2026-08-26 04:56

from django.db import migrations, models


def _mark_existing_quick_sends(apps, schema_editor):
    """Rows the one-click button created before this field existed (0114 era)
    are recognizable by the note it writes. Marking them keeps their
    duplicate-send guard intact under the new constraint-based claim. Only the
    first row per (template, record) is marked, so a pre-existing duplicate
    (possible in the 0114 era via delete-then-resend) cannot fail the
    constraint that is added right after this runs."""
    FollowUp = apps.get_model('core', 'FollowUp')
    seen = set()
    for fu in FollowUp.objects.filter(note__startswith='Sent "', done_at__isnull=False,
                                      template__isnull=False).order_by('created_at'):
        key = (fu.template_id, fu.work_order_id) if fu.work_order_id else (fu.template_id, None, fu.ticket_id)
        if key in seen:
            continue
        seen.add(key)
        fu.via_quick_send = True
        fu.save(update_fields=['via_quick_send'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_emailtemplate_quick_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='via_quick_send',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_mark_existing_quick_sends, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(condition=models.Q(('via_quick_send', True), ('work_order__isnull', False)), fields=('template', 'work_order'), name='one_quick_send_per_template_per_work_order'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket__isnull', False), ('via_quick_send', True), ('work_order__isnull', True)), fields=('template', 'ticket'), name='one_quick_send_per_template_per_ticket'),
        ),
    ]
