# Generated by Django 5.2.17 on 2026-08-27 01:37

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


def seed_sending_addresses(apps, schema_editor):
    """Carry the old From fields into SendingAddress rows, behavior-preserving:
    email_from becomes the default row; email_sales_from (when set and
    different) becomes a second row that quotes AND receipts point at, because
    both used it before this migration. Runs before the two fields are
    dropped. Historical models skip SendingAddress.save(), so is_default is
    set explicitly here."""
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SendingAddress = apps.get_model('core', 'SendingAddress')
    site = SiteSettings.objects.first()
    if site is None:
        return
    default_email = (site.email_from or '').strip()
    sales_email = (site.email_sales_from or '').strip()
    default_row = None
    if default_email:
        default_row = SendingAddress.objects.create(
            display_name=site.company_name or '', email=default_email, is_default=True)
    if sales_email and sales_email != default_email:
        sales_row = SendingAddress.objects.create(
            display_name=site.company_name or '', email=sales_email,
            is_default=default_row is None)
        site.from_quotes = sales_row
        site.from_receipts = sales_row
        site.save(update_fields=['from_quotes', 'from_receipts'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_remove_followup_one_quick_send_per_template_per_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Shown before the address, e.g. "Shamrock Sales". Blank = address only.', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_default', models.BooleanField(default=False, help_text='Used by every kind of outgoing email that has no address of its own.')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sending addresses',
                'db_table': 'sending_addresses',
                'ordering': ['-is_default', 'email'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='from_customer_emails',
            field=models.ForeignKey(blank=True, help_text='Emails a person sends by hand from a work record or customer, and one-click follow-ups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sendingaddress'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='from_internal',
            field=models.ForeignKey(blank=True, help_text='Internal shop notifications to techs and admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sendingaddress'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='from_quotes',
            field=models.ForeignKey(blank=True, help_text='Quote emails from estimates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sendingaddress'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='from_receipts',
            field=models.ForeignKey(blank=True, help_text='Receipt emails from sales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sendingaddress'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='from_reports',
            field=models.ForeignKey(blank=True, help_text='Repair report emails from work orders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sendingaddress'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='from_ticket_events',
            field=models.ForeignKey(blank=True, help_text='Ticket event emails: auto-responder, replies, status changes, resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sendingaddress'),
        ),
        # Reads email_from / email_sales_from, so it must run before they drop.
        migrations.RunPython(seed_sending_addresses, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_sales_from',
        ),
    ]
