# Generated by Django 5.2.17 on 2026-09-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_remove_followup_one_quick_send_per_template_per_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pulled_from_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_ninja_id', ''), _negated=True), fields=('invoice_ninja_id',), name='uniq_sale_invoice_ninja_id'),
        ),
    ]
