# Generated by Django 5.2.17 on 2026-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_remove_followup_one_quick_send_per_template_per_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='billed_externally',
            field=models.BooleanField(default=False, help_text='Invoicing for this contract is handled directly in your billing system. The billing run will not prepare drafts for it.'),
        ),
    ]
