# Generated by Django 5.2.17 on 2026-08-27 02:03

import re

from django.db import migrations, models
from django.utils.html import escape


# Frozen copy of core.email_html.text_to_html, so this migration keeps
# working whatever happens to that module later. Literal text is escaped and
# its newlines become <br>; Django template tokens pass through verbatim
# (escaping a filter's quotes would break the token at render time), and
# newlines inside a token stay newlines.
_TEMPLATE_TOKEN = re.compile(r'({{.*?}}|{%.*?%})', re.S)


def _text_to_html(text):
    if not text:
        return ''
    parts = _TEMPLATE_TOKEN.split(text.replace('\r\n', '\n'))
    out = []
    for i, part in enumerate(parts):
        if i % 2:
            out.append(part)
        else:
            out.append(escape(part).replace('\n', '<br>'))
    return '<div>' + ''.join(out) + '</div>'


def convert_bodies_to_html(apps, schema_editor):
    """Every stored body converts once, so there is exactly one rendering
    path afterward. Visible output is unchanged: the same text, the same
    line breaks, now expressed as markup instead of white-space:pre-line."""
    EmailTemplate = apps.get_model('core', 'EmailTemplate')
    EmailSignature = apps.get_model('core', 'EmailSignature')
    for tmpl in EmailTemplate.objects.all():
        tmpl.body_template = _text_to_html(tmpl.body_template)
        tmpl.body_format = 'html'
        tmpl.save(update_fields=['body_template', 'body_format'])
    for sig in EmailSignature.objects.all():
        sig.body = _text_to_html(sig.body)
        sig.body_format = 'html'
        sig.save(update_fields=['body', 'body_format'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_sending_addresses'),
    ]

    operations = [
        # Existing rows land as 'text' (their bodies are still plain), then
        # the data step converts each one and flips it to 'html'. New rows
        # created after this migration carry the model default, 'html'.
        migrations.AddField(
            model_name='emailsignature',
            name='body_format',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML')], default='text', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='body_format',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML')], default='text', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailsignature',
            name='body_format',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML')], default='html', max_length=5),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_format',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML')], default='html', max_length=5),
        ),
        migrations.AlterField(
            model_name='emailsignature',
            name='body',
            field=models.TextField(help_text='Appended below the email body.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_template',
            field=models.TextField(help_text='Email body (HTML from the formatting editor). Same template variables available.'),
        ),
        migrations.RunPython(convert_bodies_to_html, migrations.RunPython.noop),
    ]
