# Generated by Django 5.2.17 on 2026-09-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_sale_pulled_from_in'),
        ('core', '0118_email_html_bodies'),
    ]

    operations = [
    ]
