# Generated by Django 5.2.17 on 2026-09-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_merge_0117_sale_pulled_from_in_0118_email_html_bodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='PNG or JPG. Displayed on quotes, receipts, and repair reports.', null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Logo shown in the nav bar. PNG recommended. Leave blank to show text.', null=True, upload_to='site/'),
        ),
    ]
