"""Backup destination configuration + status, for Settings → Maintenance → Backups.

The nightly backup itself runs OUTSIDE Django (``scripts/mb_backup.sh`` on a
systemd timer) so it survives even when the web app is down. This module is the
seam between the admin UI and that shell script: on save, Django renders two
plain files the *dumb* script reads —

  * ``backup-config.env``  — sourced by the script (offsite type, paths, retention)
  * ``.rclone.conf``       — the rclone remote for the S3-compatible case

— and reads back ``logs/backup-status.json`` (written by the script on each run)
for the read-only status panel. Same "Django writes a file, a shell script reads
it" pattern as ``core/update_ops.py`` / ``HEALTHCHECKS_URL``. No sudo, no shell
from the web process (the one exception is the admin-triggered ``test_destination``
probe, a quick read mirroring the Invoice Ninja "Test Connection" button).

Secret-bearing files (``.rclone.conf`` holds the S3 secret) are written 0600.
"""
import json
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from django.conf import settings

# The rclone remote name we render into .rclone.conf and reference from the
# manifest. Fixed — there is exactly one configurable offsite destination.
RCLONE_REMOTE_NAME = 'mbbackup'

# A run is "in progress" from the moment the UI queues it until the one-shot
# service (or mb_backup.sh) writes a terminal state. Blocks a second trigger.
IN_PROGRESS_STATES = {'queued', 'running'}


def _base_dir() -> Path:
    return Path(settings.BASE_DIR)


def _logs_dir() -> Path:
    return _base_dir() / 'logs'


def rclone_conf_path() -> Path:
    # scripts/mb_backup.sh already expects the rclone config at $APP/.rclone.conf.
    return _base_dir() / '.rclone.conf'


def manifest_path() -> Path:
    return _base_dir() / 'backup-config.env'


def status_path() -> Path:
    return _logs_dir() / 'backup-status.json'


def trigger_path() -> Path:
    return _logs_dir() / 'backup-trigger'


def rclone_bin() -> Path:
    return _base_dir() / 'bin' / 'rclone'


def _write_600(path: Path, text: str) -> None:
    """Write a (possibly secret-bearing) file with owner-only permissions."""
    path.write_text(text)
    try:
        os.chmod(path, 0o600)
    except OSError:
        # Non-POSIX or permission quirk — content is written; perms are best-effort.
        pass


def rclone_remote_target(site) -> str:
    """The ``remote:bucket/path`` string for the S3 case ('' otherwise)."""
    if not site.backup_offsite_enabled or not site.backup_s3_bucket:
        return ''
    target = f'{RCLONE_REMOTE_NAME}:{site.backup_s3_bucket}'
    prefix = (site.backup_s3_path or '').strip('/')
    if prefix:
        target = f'{target}/{prefix}'
    return target


def render_config(site) -> None:
    """Render backup-config.env (always) and .rclone.conf (S3 only) from settings.

    Called after the Backups settings form saves and on deploy. Safe to call
    repeatedly — it fully rewrites both files from the current SiteSettings state.
    The MB VM is never a destination; these files describe the onsite/offsite
    destinations + retention + schedule that the shell scripts consume.
    """
    _logs_dir().mkdir(parents=True, exist_ok=True)

    if site.backup_offsite_enabled:
        remote_target = rclone_remote_target(site)
        conf = (
            f'[{RCLONE_REMOTE_NAME}]\n'
            'type = s3\n'
            'provider = Other\n'
            f'access_key_id = {site.backup_s3_access_key}\n'
            f'secret_access_key = {site.backup_s3_secret_key}\n'
            f'endpoint = {site.backup_s3_endpoint}\n'
            f'region = {site.backup_s3_region}\n'
        )
        _write_600(rclone_conf_path(), conf)
    else:
        remote_target = ''
        # Don't leave a stale remote+secret lying around when S3 is switched off.
        try:
            rclone_conf_path().unlink()
        except FileNotFoundError:
            pass

    onsite_path = site.backup_onsite_path if site.backup_onsite_enabled else ''
    manifest = (
        '# Generated by Murphy\'s Bench (Settings → Maintenance → Backups). Do not edit by hand.\n'
        f'BACKUP_ONSITE_ENABLED="{1 if site.backup_onsite_enabled else 0}"\n'
        f'BACKUP_ONSITE_PATH="{onsite_path}"\n'
        f'BACKUP_ONSITE_RETENTION_MODE="{site.backup_onsite_retention_mode}"\n'
        f'BACKUP_ONSITE_RETENTION_VALUE="{int(site.backup_onsite_retention_value)}"\n'
        f'BACKUP_ONSITE_SCHEDULE_DAYS="{site.backup_onsite_schedule_days or "daily"}"\n'
        f'BACKUP_ONSITE_SCHEDULE_TIMES="{site.backup_onsite_schedule_times or "02:00"}"\n'
        f'BACKUP_OFFSITE_ENABLED="{1 if site.backup_offsite_enabled else 0}"\n'
        f'BACKUP_RCLONE_REMOTE="{remote_target}"\n'
        f'BACKUP_OFFSITE_RETENTION_MODE="{site.backup_offsite_retention_mode}"\n'
        f'BACKUP_OFFSITE_RETENTION_VALUE="{int(site.backup_offsite_retention_value)}"\n'
        f'BACKUP_OFFSITE_SCHEDULE_DAYS="{site.backup_offsite_schedule_days or "daily"}"\n'
        f'BACKUP_OFFSITE_SCHEDULE_TIMES="{site.backup_offsite_schedule_times or "02:00"}"\n'
    )
    # The manifest itself carries no secrets, but keep it owner-only for consistency.
    _write_600(manifest_path(), manifest)


def read_status() -> dict:
    """Last backup run status written by mb_backup.sh. {'state': 'never'} if none."""
    try:
        data = json.loads(status_path().read_text())
        if isinstance(data, dict) and data.get('state'):
            return data
    except Exception:
        pass
    return {'state': 'never'}


def is_running() -> bool:
    return read_status().get('state') in IN_PROGRESS_STATES


def request_backup_now() -> bool:
    """Queue an out-of-band backup run. Writes a 'queued' status marker and the
    empty trigger file the systemd .path unit watches (a web request must not run
    the long backup in-process). Refuses (returns False) if a run is already going."""
    if is_running():
        return False
    logs = _logs_dir()
    logs.mkdir(parents=True, exist_ok=True)
    status_path().write_text(json.dumps({
        'state': 'queued',
        'started_at': datetime.now(timezone.utc).isoformat(),
    }))
    trigger_path().write_text('')
    return True


def test_destination(site, which):
    """Probe a configured destination. `which` in {'onsite','offsite'}.
    Returns (ok: bool, message: str). Mirrors the Invoice Ninja "Test Connection"
    button — a quick read from the web process.
    """
    if which == 'onsite':
        if not site.backup_onsite_enabled:
            return False, 'Onsite backup is not enabled.'
        path = (site.backup_onsite_path or '').strip()
        if not path:
            return False, 'No onsite path is set.'
        p = Path(path)
        if not p.is_dir():
            return False, f'Path does not exist or is not a directory: {path}'
        if not os.access(path, os.W_OK):
            return False, f'Path is not writable: {path}'
        return True, f'Onsite destination is reachable and writable: {path}'

    if which == 'offsite':
        if not site.backup_offsite_enabled:
            return False, 'Offsite backup is not enabled.'
        if not site.backup_s3_bucket:
            return False, 'No S3 bucket is set.'
        # Re-render so the probe uses exactly what a real run would.
        render_config(site)
        binary = rclone_bin()
        if not binary.exists():
            return False, (
                'rclone is not installed on the server (expected at bin/rclone) — '
                'the destination is saved but cannot be tested from here.'
            )
        remote = f'{RCLONE_REMOTE_NAME}:{site.backup_s3_bucket}'
        try:
            out = subprocess.run(
                [str(binary), '--config', str(rclone_conf_path()), 'lsd', remote],
                capture_output=True, text=True, timeout=30,
            )
        except Exception as exc:  # subprocess failure, timeout, etc.
            return False, f'Could not run rclone: {exc}'
        if out.returncode == 0:
            return True, f'S3 destination reachable: bucket "{site.backup_s3_bucket}".'
        detail = (out.stderr or out.stdout or '').strip().splitlines()
        msg = detail[-1] if detail else f'exit code {out.returncode}'
        return False, f'S3 test failed: {msg}'

    return False, f'Unknown destination: {which}'
