#!/usr/bin/env bash
# One-shot installer for Murphy's Bench — scripts the app-bring-up half of
# INSTALL.md so a fresh box goes from "code is here" to "app runs, migrated,
# superuser created, tests pass" in one fail-loud command. No code-reading.
#
#   git clone <repo> /opt/murphys-bench
#   cd /opt/murphys-bench && scripts/setup.sh
#
# Targets the Debian/Ubuntu (apt) family with Python >= 3.10. It does NOT wire up
# gunicorn/nginx/Cloudflare — those are per-box decisions; it prints the exact
# remaining steps (with deploy/demo configs) at the end.
#
# Flags / env:
#   --skip-apt        don't install system packages (already present, or no sudo)
#   --skip-tests      don't run the pytest smoke check at the end
#   --noinput         non-interactive: skip the createsuperuser prompt
#   ALLOWED_HOSTS=..  comma list for .env (default: localhost,127.0.0.1)
#   COMPANY_NAME=..   .env COMPANY_NAME (default: Murphy's Bench)
#
# Safe to re-run: an existing .env is never overwritten; deps/migrate/build are
# idempotent.
set -euo pipefail

APP="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP"
VENV="$APP/venv/bin"

SKIP_APT=0; SKIP_TESTS=0; NOINPUT=0
for a in "$@"; do
  case "$a" in
    --skip-apt) SKIP_APT=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    --noinput) NOINPUT=1 ;;
    *) echo "setup: unknown arg '$a'" >&2; exit 2 ;;
  esac
done

log()  { echo "$(date '+%F %T') setup: $*"; }
fail() { echo "SETUP FAILED: $*" >&2; exit 1; }

[ -f manage.py ] || fail "no manage.py in $APP — run this from the cloned repo root"

# 0) Preflight.
command -v git >/dev/null || fail "git not installed"
if [ "$SKIP_APT" = 0 ]; then
    command -v apt-get >/dev/null || fail "this installer targets the apt (Debian/Ubuntu) family; \
on another distro install python3/venv/pip/nginx/git/logrotate yourself and re-run with --skip-apt"
fi
PYBIN="$(command -v python3 || true)"
[ -n "$PYBIN" ] || fail "python3 not found"
PYVER="$("$PYBIN" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
"$PYBIN" -c 'import sys; raise SystemExit(0 if sys.version_info[:2] >= (3,10) else 1)' \
    || fail "Python >= 3.10 required (found $PYVER)"
log "python $PYVER OK"

# 1) System packages.
if [ "$SKIP_APT" = 0 ]; then
    log "installing system packages (sudo)..."
    sudo apt-get update -qq || fail "apt update failed"
    sudo apt-get install -y -qq python3 python3-venv python3-pip nginx git logrotate curl \
        || fail "apt install failed"
else
    log "skipping apt (--skip-apt)"
fi

# 2) Python virtualenv + dependencies.
if [ ! -x "$VENV/python" ]; then
    log "creating virtualenv..."
    "$PYBIN" -m venv venv || fail "venv creation failed"
fi
log "installing Python dependencies..."
"$VENV/pip" install --upgrade -q pip || fail "pip self-upgrade failed"
"$VENV/pip" install -q -r requirements.txt || fail "pip install -r requirements.txt failed"

# 3) Runtime directories the app writes to (logs/ is required at startup).
mkdir -p logs media protected backups
log "runtime dirs ready (logs media protected backups)"

# 4) .env — create with generated keys if absent; NEVER clobber an existing one.
if [ -f .env ]; then
    log ".env already exists — leaving it untouched"
else
    log "generating .env with fresh per-instance keys (SQLite default)..."
    SECRET_KEY="$("$VENV/python" -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')" \
        || fail "could not generate SECRET_KEY"
    FERNET_KEY="$("$VENV/python" -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')" \
        || fail "could not generate FIELD_ENCRYPTION_KEY"
    cat > .env <<ENVEOF
# Murphy's Bench environment — generated by scripts/setup.sh on $(date '+%F %T').
# This file holds all secrets. Never commit it. Keep perms at 600.
DEBUG=False
SECRET_KEY=${SECRET_KEY}
FIELD_ENCRYPTION_KEY=${FERNET_KEY}
ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
COMPANY_NAME=${COMPANY_NAME:-Murphy's Bench}
TIMEZONE=America/Los_Angeles

# Database: SQLite by default (a file at db.sqlite3 — no DB server needed).
# To use PostgreSQL instead, see INSTALL.md step 5 and set DB_ENGINE=... here.

# HTTPS hardening — turn ON only once TLS is confirmed end-to-end (reverse proxy
# / Cloudflare). On a plain-HTTP LAN box leave these OFF or internal access breaks.
# CSRF_TRUSTED_ORIGINS=https://your.hostname
# SECURE_SSL_REDIRECT=True
# SESSION_COOKIE_SECURE=True
# CSRF_COOKIE_SECURE=True
ENVEOF
    chmod 600 .env
    log ".env created (chmod 600)"
fi

# 5) Build the self-hosted Tailwind stylesheet BEFORE collectstatic (no Node).
log "building CSS (self-hosted Tailwind)..."
"$APP/scripts/build_css.sh" || fail "CSS build failed"

# 6) Initialize Django.
log "running migrations..."
"$VENV/python" manage.py migrate --noinput || fail "migrate failed"
log "collecting static files..."
"$VENV/python" manage.py collectstatic --noinput >/dev/null || fail "collectstatic failed"

# 7) Superuser (interactive, only if none exists yet).
HAS_SU="$("$VENV/python" manage.py shell -c \
    'from django.contrib.auth import get_user_model as g; print(g().objects.filter(is_superuser=True).exists())' \
    2>/dev/null | tail -1 || echo True)"
if [ "$HAS_SU" = "False" ]; then
    if [ "$NOINPUT" = 1 ]; then
        log "no superuser yet — skipping (--noinput). Create one later: venv/bin/python manage.py createsuperuser"
    else
        log "no superuser found — creating one now (Ctrl-C to skip)."
        "$VENV/python" manage.py createsuperuser || log "createsuperuser skipped/failed — create one later with: venv/bin/python manage.py createsuperuser"
    fi
else
    log "superuser already exists — skipping createsuperuser"
fi

# 8) Smoke checks.
log "running deploy check (HTTPS warnings are expected on a plain-HTTP box)..."
"$VENV/python" manage.py check || fail "manage.py check failed"
if [ "$SKIP_TESTS" = 0 ]; then
    log "running the test suite (smoke)..."
    "$VENV/python" -m pytest -q || fail "test suite failed — do not deploy until green"
else
    log "skipping tests (--skip-tests)"
fi

# 9) Done — print the remaining deployment-specific steps.
cat <<DONE

$(date '+%F %T') setup: APP LAYER READY at $APP

⚠ SAVE YOUR ENCRYPTION KEY
  FIELD_ENCRYPTION_KEY in $APP/.env protects all stored credentials. If you lose
  it, encrypted data is permanently unrecoverable. Copy it into a password
  manager NOW (also save SECRET_KEY).

Remaining (per-box, need sudo — see INSTALL.md §8–10 and deploy/demo/):
  1. Gunicorn systemd unit  -> /etc/systemd/system/murphys-bench.service
     (sets EnvironmentFile=$APP/.env, binds unix:$APP/murphys.sock)
     sudo systemctl enable --now murphys-bench
  2. Nginx reverse proxy     -> /etc/nginx/sites-available/murphys-bench
     (static -> $APP/staticfiles/, proxy_pass to the socket)
     sudo nginx -t && sudo systemctl reload nginx
  3. (Optional) Cloudflare Tunnel for public HTTPS                  (INSTALL.md §9)
  4. (Optional) Scheduled-job timers: backup / inbound-email / SLA  (deploy/README.md)

Then browse to the host and log in as your superuser.
DONE
